blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title=StringField("Title",validators=[DataRequired()])
    content=TextAreaField("Content",validators=[DataRequired()])
    post=SubmitField("Post")

blog/main/routes.py
from flask import Blueprint
from flask import render_template,request
from blog.models import Post




main=Blueprint("main",__name__)


@main.route("/")
@main.route("/home")
def home():
    page= request.args.get('page',1,type=int)
    posts=Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("home.html",posts=posts)


@main.route("/about")
def about():
    return render_template("about.html")

blog/posts/routes.py
from flask import render_template,url_for,flash,redirect,request,abort,Blueprint
from blog.posts.forms import PostForm
from blog import db
from blog.models import Post
from flask_login import current_user,login_required

posts=Blueprint("posts",__name__)



@posts.route("/post/new",methods=["POST","GET"])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        post= Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("You have successfully created a new Post!","success")
        return redirect(url_for("main.home"))
    return render_template("create_post.html",form=form,legend="New Post")


@posts.route("/post/<int:id>")
def view_post(id):
   post=Post.query.get_or_404(id)
   return render_template("post.html",post=post)


@posts.route("/post/<int:id>/update",methods=["POST","GET"])
def update_post(id):
   

   post=Post.query.get_or_404(id)
   if post.author != current_user:
       abort(403)

   form=PostForm()
   if form.validate_on_submit():
       post.title=form.title.data
       post.content=form.content.data
       db.session.commit()
       flash("Post Updated Successfully","success")
       return redirect(url_for("posts.view_post",id=post.id))
   elif request.method =="GET":
        form.title.data=post.title
        form.content.data=post.content

   return render_template("create_post.html",form=form,legend="Update Post")
 


@posts.route("/post/<int:id>/delete",methods=["POST","GET"])
def delete_post(id):
   post=Post.query.get_or_404(id)
   if post.author != current_user:
       abort(403)
   
   db.session.delete(post)
   db.session.commit()
   flash("Your Post has been deleted!","success")
   return redirect(url_for('main.home'))

blog/users/routes.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from blog.users.forms import RegistrationForm,LoginForm,UpdateAccountForm,RequestResetForm,PasswordResetForm
from blog import bcrypt,db,mail
from blog.models import User,Post
from flask_login import current_user,login_user,logout_user,login_required
from blog.users.utils import save_p_image,send_reset_email

users=Blueprint("users",__name__)


@users.route("/register",methods=["POST","GET"])
def register():
    if current_user.is_authenticated:
        return redirect('home')
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Yor Account has been successfully Created! Now You are able to LogIn.","success")
        return redirect(url_for('users.login'))
    return render_template("register.html",form=form)


@users.route("/login",methods=["POST","GET"])
def login():
    if current_user.is_authenticated:
        return redirect('home')
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            flash(f"Yor Account has been successfully LoggedIn.","success")
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login Unsuccessful! please check email and Password.","danger")
            return redirect(url_for('users.login'))
    return render_template("login.html",form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account",methods=["POST","GET"])
@login_required
def account():
    form=UpdateAccountForm()
    p_image=url_for("static",filename="profilepics/"+current_user.p_image)
    if form.validate_on_submit():
        if form.p_image.data:
            pfimage=save_p_image(form.p_image.data)
            current_user.p_image=pfimage

        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash("Your Details are Updated Successfully.","success")
        return redirect(url_for("users.account"))
    elif request.method=="GET":
        form.username.data=current_user.username
        form.email.data=current_user.email
    return render_template("account.html",form=form,p_image=p_image)

@users.route("/user/<string:username>")
def user_posts(username):
    page= request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("user_posts.html",posts=posts,user=user)



 
@users.route("/reset_password",methods=["POST","GET"])
def request_reset():
    if current_user.is_authenticated:
        return redirect('home')
    form=RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has sent with instructions for password reset","success")
        return redirect(url_for("users.login"))
    return render_template("request_reset.html",form=form)


@users.route("/reset_password/<token>",methods=["POST","GET"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect('home')
    user=User.verify_reset_token(token)
    if user is None:
        flash("The Link has expired or invalid!","warning")
        return redirect(url_for("users.request_reset"))
    form=PasswordResetForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash(f"Your Password Updated Successfully!","success")
        return redirect(url_for('users.login'))
    return render_template("reset_password.html",form=form)

blog/templates/about.html
{% extends 'base.html' %}
{% block body %}
    
{% endblock body %}

blog/templates/account.html
{% extends 'base.html' %}
{% block body %}
<div class="card mb-3 p-2 container" style="max-width: 540px; margin-top: 5%;">   
  <div class="d-inline-flex  flex-row p-2 ms-3 justify-content-cente" >
    <div class="d-flex align-content-center flex-wrap">
      <img src="{{p_image}}" class="img-fluid  " style="height: 80px; width: 80px; border-radius: 100%;">
    </div>
    
      <div class="card-body align-content-start ">
        <h5 class="card-title">{{current_user.username}}</h5>
        <p class="card-text">{{current_user.email}}</p>
      </div>
  </div>
  <form method="post"  action="" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <fieldset class="container " >
    <legend class="border-bottom mb-3">Account Info</legend>
    
    <div style="margin-bottom: 1rem;">
      {{form.username.label(class="form-control-label")}}

      {% if form.username.errors %}
      {{form.username(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.username.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>

      {% else %}
      {{form.username(class="form-control ")}}
      {% endif %}

    </div>
    <div style="margin-bottom: 1rem;">
      {{form.email.label(class="form-control-label")}}
      {% if form.email.errors %}
      {{form.email(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.email(class="form-control ")}}
      {% endif %}
    </div>
    <div style="margin-bottom: 1rem;">
      {{form.p_image.label()}}
      <div class="m-2">
      {{form.p_image(class="form-control-file ")}}
      {% if form.p_image.errors %}
      <div class="m-1">
      {% for error in form.p_image.errors %}
          <span class="text-danger ">{{error}}</span>
      {% endfor %}
        </div>
      {% endif %}
      </div>
    </div>
    <div style="margin-bottom: 1rem; margin-left: 1rex;">
        {{form.update(class="btn btn-outline-info")}}</div>

  </fieldset>

</form>

</div>
{% endblock body %}

blog/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

  <link rel="stylesheet" href="/static/main.css">
</head>
<nav class="navbar navbar-expand-lg  fixed-top" style="background-color: rgb(0, 90, 142);">
  <div class="container-fluid" style="margin-left: 10rem;">
    <a class="navbar-brand text-white " href="/">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" href="{{url_for('main.home')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{{url_for('main.about')}}">About</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 " style="margin-left: 40vw;">

        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{url_for('posts.new_post')}}">New Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{url_for('users.account')}}">account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{url_for('users.logout')}}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{url_for('users.login')}}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{url_for('users.register')}}">Register</a>
        </li>

        {% endif %}

      </ul>
    </div>
  </div>
</nav>

<body class="">
  <div aria-live="polite" aria-atomic="true" class="position-relative">

    <div class="toast-container position-fixed top-0 end-0 p-3">

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="toast align-items-center text-bg-{{ category }} border-0  show  " role="alert" >
        <div class="d-flex">
          <div class="toast-body ">
            {{ message }}
          </div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
        </div>
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

    </div>
  </div>

  {% block body %}

  {% endblock body %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(el => new bootstrap.Popover(el))
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
      myInput.focus()
    })

    var toastElList = [].slice.call(document.querySelectorAll('.toast'))
    var toastList = toastElList.map(function (toastEl) {
      return new bootstrap.Toast(toastEl, option)
    })



  </script>

</body>

</html>

blog/templates/create_post.html
{% extends 'base.html' %}
{% block body %}
<form method="post" action="" class="container w-50 ">
  {{ form.hidden_tag() }}
  
  <fieldset class="container rounded" style="margin-top: 6rem; padding: 15px 25px 20px 25px; border: 1px solid grey;">
    <div class="mb-3 border-bottom border-3">
    <h5>{{legend}}</h5>
    
  </div>

    <div style="margin-bottom: 1rem;">
      {{form.title.label(class="form-control-label")}}
      {% if form.title.errors %}
      {{form.title(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.title.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.title(class="form-control ")}}
      {% endif %}
    </div>
    <div style="margin-bottom: 1rem;">
      {{form.content.label(class="form-control-label")}}
      {% if form.content.errors %}
      {{form.content(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.content.errors %}
        <span>{{error}}</span>
        {% endfor %}
        {% else %}
        {{form.content(class="form-control ")}}
        {% endif %}
      </div>
    </div>
    
    <div style="margin-bottom: 1rem;">
      {{form.post(class="btn btn-outline-info")}}</div>
  </fieldset>

</form>

{% endblock body %}

blog/templates/home.html
{% extends 'base.html' %}
{% block body %}

<div class="fixed-top " style="width: 30%;  left: 70%; top: 10%;">
  <div class="card  " style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Our Sidebar</h5>
      <p class="card-text">You can put any information you'd like.</p>
    </div>
    <ul class="list-group list-group-flush mb-3 ms-3 me-3 border rounded">
      <a href="#" class="list-group-item">Latest Posts</a>
      <a href="#" class="list-group-item">Announcements</a>
      <a href="#" class="list-group-item">Calenders</a>
      <a href="#" class="list-group-item">etc</a>
    </ul>

  </div>
</div>



<div class="" style="width: 70%; margin-left: 10%; margin-top: 5%;">
  {% for post in posts.items %}
  <div class="mt-3 w-50 container  ">
    <div class="card flex-md-row   box-shadow h-md-250 ">
      <div class="card-body d-flex flex-column align-items-start ">

        <legend class="border-bottom ">
          <div class="d-inline-block d-flex  align-items-center text-primary  gap-3 mb-2">
           <a href="{{url_for('users.user_posts',username=post.author.username)}}"> <img src="{{url_for('static',filename='profilepics/'+post.author.p_image)}}"
              style=" height: 40px; width: 40px; border-radius: 100%;"></a>
            <div class="d-flex  align-items-center">
              <a href="{{url_for('users.user_posts',username=post.author.username)}}"
                style="text-decoration: none; margin-right: 5px; font-size: large; ">{{post.author.username}}
              </a>
              <small class=" text-muted " style="font-size: small;">{{post.date_posted.strftime('%d-%m-%Y')}}</small>
            </div>
          </div>
        </legend>




        <h3 class="mb-0">
          <a class="" style="text-decoration: none;" 
            href="{{url_for('posts.view_post',id=post.id)}}">{{post.title}}</a>
        </h3>
        <p class="card-text mb-auto">{{post.content}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


<div class="container d-flex justify-content-center ms-2 gap-1 align-items-end">
  {% for page_no in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}

  {% if page_no %}

  {% if posts.page == page_no %}
  <a href="{{url_for('main.home',page=page_no)}}" class="btn btn-info mt-4 mb-4">{{page_no}}</a>
  {% else %}
  <a href="{{url_for('main.home',page=page_no)}}" class="btn btn-outline-info mt-4 mb-4">{{page_no}}</a>
  {% endif %}

  {% else %}
  ...
  {% endif %}

  {% endfor %}
</div>





{% endblock body %}

blog/templates/login.html
{% extends 'base.html' %}
{% block body %}
<form method="post" action="" class="container w-50">
  {{ form.hidden_tag() }}
  
  <fieldset class="container rounded" style="margin-top: 6rem; padding: 18px 25px 20px 25px; border: 1px solid grey;">
    <div class="mb-3 border-bottom border-3">
    <h5>Log In</h5>
    
    
  </div>

    <div style="margin-bottom: 1rem;">
      {{form.email.label(class="form-control-label")}}
      {% if form.email.errors %}
      {{form.email(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.email(class="form-control ")}}
      {% endif %}
    </div>
    <div style="margin-bottom: 1rem;">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
      {{form.password(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.password.errors %}
        <span>{{error}}</span>
        {% endfor %}
        {% else %}
        {{form.password(class="form-control ")}}
        {% endif %}
      </div>
    </div>
    <div class="form-check mb-3">
      <input class="form-check-input" type="checkbox" value="" id="checkDefault">
      <label class="form-check-label" for="checkDefault">
        Remember Me
      </label>
    </div>
    <div style="margin-bottom: 1rem;">
      {{form.submit(class="btn btn-outline-info")}}
      
    </div>
    <div">
     <a href="{{url_for('users.request_reset')}}" style="text-decoration: none;">Forgot Password?</a>
      
    </div>
  </fieldset>

  <div class="mt-3">
    <span>Need an account ?</span>  <a href="{{url_for('users.register')}}" style="text-decoration: none;">Sign up now</a>
  </div>

</form>

{% endblock body %}

blog/templates/post.html
{% extends 'base.html' %}
{% block body %}
<div class="d-flex justify-content-center mt-5" style="gap: 5rem;">
    <div class="d-inline-block " style="width: 40%;">
        <div class="mt-4">
            <div class="card flex-md-row  box-shadow h-md-250 ">
                <div class="card-body d-flex flex-column align-items-start ">

                    <legend class="border-bottom ">
                        <div class="d-inline-block d-flex  align-items-center text-primary  gap-3 mb-2">
                            <img src="{{url_for('static',filename='profilepics/'+post.author.p_image)}}" class=" "
                                style=" height: 40px; width: 40px; border-radius: 100%;">
                            <div class="d-flex  align-items-center">
                                <a href="{{url_for('users.user_posts',username=post.author.username)}}"
                                    style="text-decoration: none; margin-right: 5px; font-size: large; ">{{post.author.username}}
                                </a>
                                <small class=" text-muted "
                                    style="font-size: small;">{{post.date_posted.strftime('%d-%m-%Y')}}</small>
                            </div>
                        </div>
                    </legend>



                    <div>
                        <h3 class="mb-0">
                            <a class="text-dark" style="text-decoration: none;" href="#">{{post.title}}</a>
                        </h3>
                        <p class="card-text mb-auto">{{post.content}}</p>
                            
                       
                        <div class="mt-3">
                            <a class="btn btn-secondary" href="{{url_for('posts.update_post',id=post.id)}}">Update</a>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#deleteModal">
                               Delete
                            </button>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>

    </div>



</div>


<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{url_for('posts.delete_post',id=post.id)}}" method="post">
                    <input class="btn btn-danger" type="submit" value="Delete" >
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock body %}

blog/templates/register.html
{% extends 'base.html' %}

{% block body %}
<form method="post"  action=""  class="w-50 container">
  {{ form.hidden_tag() }}
  <fieldset class="container rounded" style="margin-top: 6rem; padding: 15px 25px 20px 25px; border: 1px solid grey;">
    <div class="mb-3 border-bottom border-3">
    <h5>Register</h5>
  </div>
    <div style="margin-bottom: 1rem;">
      {{form.username.label(class="form-control-label")}}

      {% if form.username.errors %}
      {{form.username(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.username.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>

      {% else %}
      {{form.username(class="form-control ")}}
      {% endif %}

    </div>
    <div style="margin-bottom: 1rem;">
      {{form.email.label(class="form-control-label")}}
      {% if form.email.errors %}
      {{form.email(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.email(class="form-control ")}}
      {% endif %}
    </div>
    <div style="margin-bottom: 1rem;">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
      {{form.password(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.password.errors %}
        <span>{{error}}</span>
        {% endfor %}
        {% else %}
        {{form.password(class="form-control ")}}
        {% endif %}
      </div>
      <div style="margin-bottom: 1rem;">
        {{form.confirm_password.label(class="form-control-label")}}
        {% if form.confirm_password.errors %}
        {{form.confirm_password(class="form-control is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %}
        {{form.confirm_password(class="form-control ")}}
        {% endif %}
      </div>
      <div style="margin-bottom: 1rem;">
        {{form.submit(class="btn btn-outline-info")}}</div>
  </fieldset>

</form>

<div class="container text-center " style="margin-top: 1rem; margin-left: -130px;">
  <p>Already have an account ? <a href="{{url_for('users.login')}}" style="text-decoration: none;">Sign In</a></p>
</div>




{% endblock body %}

blog/templates/request_reset.html
{% extends 'base.html' %}
{% block body %}
<form method="post" action="" class="container w-50">
  {{ form.hidden_tag() }}
  
  <fieldset class="container rounded" style="margin-top: 6rem; padding: 15px 25px 20px 25px; border: 1px solid grey;">
    <div class="mb-3 border-bottom border-3">
    <h5>Request Reset Password</h5>
    
    
  </div>

    <div style="margin-bottom: 1rem;">
      {{form.email.label(class="form-control-label")}}
      {% if form.email.errors %}
      {{form.email(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.email(class="form-control ")}}
      {% endif %}
    </div>

    <div style="margin-bottom: 1rem;">
      {{form.submit(class="btn btn-outline-info")}}</div>
  </fieldset>

</form>

{% endblock body %}

blog/templates/reset_password.html
{% extends 'base.html' %}

{% block body %}
<form method="post"  action=""  class="w-50 container">
  {{ form.hidden_tag() }}
  <fieldset class="container rounded" style="margin-top: 6rem; padding: 15px 25px 20px 25px; border: 1px solid grey;">
    <div class="mb-3 border-bottom border-3">
    <h5>Reset Password</h5>
  </div>

   
    <div style="margin-bottom: 1rem;">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
      {{form.password(class="form-control is-invalid")}}
      <div class="invalid-feedback">
        {% for error in form.password.errors %}
        <span>{{error}}</span>
        {% endfor %}
        {% else %}
        {{form.password(class="form-control ")}}
        {% endif %}
      </div>
      <div style="margin-bottom: 1rem;">
        {{form.confirm_password.label(class="form-control-label")}}
        {% if form.confirm_password.errors %}
        {{form.confirm_password(class="form-control is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %}
        {{form.confirm_password(class="form-control ")}}
        {% endif %}
      </div>
      <div style="margin-bottom: 1rem;">
        {{form.submit(class="btn btn-outline-info")}}</div>
  </fieldset>

</form>


{% endblock body %}

blog/templates/user_posts.html
{% extends 'base.html' %}
{% block body %}
<div class="container d-flex ms-4 justify-content-center " style="margin-top: 5%;">
<h2>Posts by {{user.username}} ({{posts.total}})</h2>
</div>
<div class="fixed-top " style="width: 30%;  left: 70%; top: 10%;">
  <div class="card  " style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Our Sidebar</h5>
      <p class="card-text">You can put any information you'd like.</p>
    </div>
    <ul class="list-group list-group-flush mb-3 ms-3 me-3 border rounded">
      <a href="#" class="list-group-item">Latest Posts</a>
      <a href="#" class="list-group-item">Announcements</a>
      <a href="#" class="list-group-item">Calenders</a>
      <a href="#" class="list-group-item">etc</a>
    </ul>

  </div>
</div>

<div class="" style="width: 70%; margin-left: 10%; " >
  {% for post in posts.items %}
  <div class="mt-3 w-50 container  ">
    <div class="card flex-md-row   box-shadow h-md-250 ">
      <div class="card-body d-flex flex-column align-items-start ">

        <legend class="border-bottom ">
          <div class="d-inline-block d-flex  align-items-center text-primary  gap-3 mb-2">
            <img src="{{url_for('static',filename='profilepics/'+post.author.p_image)}}" class=" "
              style=" height: 40px; width: 40px; border-radius: 100%;">
            <div class="d-flex  align-items-center">
              <a href="{{url_for('users.user_posts',username=post.author.username)}}" style="text-decoration: none; margin-right: 5px; font-size: large; ">{{post.author.username}}
              </a>
              <small class=" text-muted " style="font-size: small;">{{post.date_posted.strftime('%d-%m-%Y')}}</small>
            </div>
          </div>
        </legend>




        <h3 class="mb-0">
          <a class="text-dark" style="text-decoration: none;"
            href="{{url_for('posts.view_post',id=post.id)}}">{{post.title}}</a>
        </h3>
        <p class="card-text mb-auto">{{post.content}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>




<div class="container d-flex justify-content-center  ms-2 gap-1 align-items-end "  >
{% for page_no in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}

{% if page_no %}

  {% if posts.page==page_no %}
    <a href="{{url_for('users.user_posts',username=user.username,page=page_no)}}" class="btn btn-info mt-4 mb-4">{{page_no}}</a>
  {% else %}
    <a href="{{url_for('users.user_posts',username=user.username,page=page_no)}}" class="btn btn-outline-info mt-4 mb-4">{{page_no}}</a>
  {% endif %}

{% else %}
    ...
{% endif %}

{% endfor %}
</div>


{% endblock body %}